backend:
  name: github
  repo: lehanism/myportfolio

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: folder: "src/pages/content"
    create: true
    fields:
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}